# Generated by Django 3.1.1 on 2020-11-06 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='expense',
            fields=[
                ('expenseid', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='usertable',
            fields=[
                ('username', models.CharField(max_length=100)),
                ('useremail', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('profession', models.CharField(max_length=100)),
                ('opbalance', models.FloatField()),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'usertable',
            },
        ),
        migrations.CreateModel(
            name='savings',
            fields=[
                ('savingsaccount', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('savingsid', models.AutoField(primary_key=True, serialize=False)),
                ('expenseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.expense')),
                ('useremail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='income',
            fields=[
                ('incomeid', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('useremail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='generalreserve',
            fields=[
                ('date', models.DateTimeField(auto_now_add=True)),
                ('assetname', models.CharField(max_length=100)),
                ('assetvalue', models.FloatField()),
                ('reserveamt', models.FloatField()),
                ('GRid', models.AutoField(primary_key=True, serialize=False)),
                ('expenseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.expense')),
                ('useremail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.usertable')),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='useremail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.usertable'),
        ),
    ]
