# Generated by Django 3.1.1 on 2020-11-06 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='credit',
            fields=[
                ('date', models.DateTimeField(auto_now_add=True)),
                ('creditaccount', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('creditbalance', models.FloatField()),
                ('incomeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.income')),
                ('useremail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.usertable')),
            ],
        ),
    ]
