# Generated by Django 3.1.1 on 2020-11-06 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='creditentry',
            fields=[
                ('amountpaid', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('creditentryid', models.AutoField(primary_key=True, serialize=False)),
                ('creditaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.credit')),
                ('expenseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.expense')),
                ('useremail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.usertable')),
            ],
        ),
    ]
