# Generated by Django 3.1.1 on 2020-11-09 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_creditentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditentry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 9, 11, 50, 24, 61855)),
        ),
    ]
