# Generated by Django 3.1.1 on 2020-11-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20201109_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditentry',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
