# Generated by Django 3.1.1 on 2020-11-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_auto_20201109_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
