# Generated by Django 3.1.1 on 2020-11-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_remove_usertable_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditentry',
            name='proof',
            field=models.FileField(default='/images/no-proof.jpg', upload_to='images'),
        ),
    ]
