# Generated by Django 3.1.1 on 2020-11-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0011_remove_creditentry_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditentry',
            name='proof',
            field=models.FileField(default='images/no-proof.png', upload_to='images'),
        ),
    ]
