# Generated by Django 3.1.1 on 2020-11-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0012_creditentry_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditentry',
            name='proof',
            field=models.FileField(default='media/images/no-proof.png', upload_to='media/images'),
        ),
    ]
