# Generated by Django 3.1.1 on 2020-11-28 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0013_auto_20201128_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditentry',
            name='proof',
        ),
    ]
