# Generated by Django 3.1.1 on 2020-11-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0015_creditentry_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='proof',
            field=models.FileField(default='images/no-proof.png', upload_to='images'),
        ),
        migrations.AddField(
            model_name='expense',
            name='proof',
            field=models.FileField(default='images/no-proof.png', upload_to='images'),
        ),
        migrations.AddField(
            model_name='generalreserve',
            name='proof',
            field=models.FileField(default='images/no-proof.png', upload_to='images'),
        ),
        migrations.AddField(
            model_name='income',
            name='proof',
            field=models.FileField(default='images/no-proof.png', upload_to='images'),
        ),
        migrations.AddField(
            model_name='savings',
            name='proof',
            field=models.FileField(default='images/no-proof.png', upload_to='images'),
        ),
    ]
