# Generated by Django 3.1.1 on 2020-12-01 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0016_auto_20201130_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='logentry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=500)),
                ('useremail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.usertable')),
            ],
        ),
    ]
