# Generated by Django 3.1.1 on 2020-12-01 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0017_logentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='logentry',
        ),
    ]
