# Generated by Django 3.1.1 on 2020-12-25 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0019_logentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='taxation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('duration', models.CharField(max_length=100)),
                ('payableamt', models.FloatField()),
                ('status', models.BooleanField()),
                ('proof', models.FileField(default='images/no-proof.png', upload_to='images')),
            ],
        ),
        migrations.AddField(
            model_name='usertable',
            name='age',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
    ]
