# Generated by Django 3.1.1 on 2020-12-26 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0020_auto_20201225_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable',
            name='age',
        ),
    ]
