# Generated by Django 3.1.1 on 2020-12-26 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0021_remove_usertable_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='age',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
    ]
