# Generated by Django 3.1.1 on 2020-12-28 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0022_usertable_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='taxation',
        ),
    ]
