# Generated by Django 3.1.1 on 2020-12-28 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0023_delete_taxation'),
    ]

    operations = [
        migrations.CreateModel(
            name='taxation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('duration', models.CharField(max_length=100)),
                ('payableamt', models.FloatField()),
                ('status', models.BooleanField()),
                ('proof', models.FileField(default='images/no-proof.png', upload_to='images')),
                ('useremail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.usertable')),
            ],
        ),
    ]
