# Generated by Django 3.1.1 on 2021-01-22 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0024_taxation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='age',
            field=models.DateField(default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
    ]
