# Generated by Django 3.1.1 on 2021-01-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0025_auto_20210122_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
