# Generated by Django 3.1.1 on 2021-01-22 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0026_auto_20210122_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable',
            name='age',
        ),
    ]
